### ISSUE TITLE
IC21 part number

### ISSUE THREAD

**Issue by furrtek** [lpollier/battmon#4]
Hello,
I stumbled upon your project on StackExchange but I don't have enough reputation to post an answer over there.
IC21 isn't from Microchip but from Mitsumi. The exact part number is MM1302F: https://www.alldatasheet.com/datasheet-pdf/pdf/92975/MITSUMI/MM1302F.html

**Comment by lpollier** [comment]
Hi Furrtek,

It looks like you have solved the IC21 component puzzle. The pinout seems to match the schematic and its function on the ERA-201B1 PCB.

In addition, the logo indicated to the package corresponds well to that of this manufacturer in the 1990s:
https://deskthority.net/wiki/Mitsumi

Finally, Sony seems to have collaborated with Mitsuba on other products from this period of the late 1990s and early 2000s:
https://en.wikipedia.org/wiki/Mitsumi_Electric

How did you find this manufacturer and the reference with the only marking 302F?

**Comment by lpollier** [comment]
Hi Furrtek,

I modified the ERA-201B1 reverse engineering schematic so that the IC21 component shows the correct part number MM1302F on version 1.3.

So I close this topic. Thanks again for this find.

**Comment by furrtek** [comment]
Hi Loïc ! Sorry I wasn't getting notifications from this thread.
I recognized the logo from having seen it in several battery-backed Gameboy cartridges.
It's indeed confusingly similar to the Microchip "M".

**Comment by lpollier** [comment]
It is interesting to know how you found out about this company and surprising that this logo is not better known in the listings of component manufacturers.

Thank you Furrtek.
