### ISSUE TITLE
No device found on scanning SMBus

### ISSUE THREAD

**Issue by kgh02017** [lpollier/battmon#6]
I couldn't read my battery info (ERA-201B1).
The reason seems that BattMon cannot detect SMBus device.

I tried to connect other I2C device (LCD1602, address=0x279 ) and scan SMbus.
This time BattMon could find the device, so its sketch works well, I think.

Could you please give me an advice to solve the problem ?

**Comment by lpollier** [comment]
Hi kgh02017,

OK, from what I understood of your context, the bq2040 gas gauge is not responding since it is probably not well powered.

So, I deduce from my assumption that your ERA-201B1 battery pack is close to dead, meaning its cells are not able to power at least the gas gauge alone.

Can you try to full recharge your battery pack before testing it with the BattMon 2.0 toolkit?

And also you should power the Arduino Uno from the USB external source of power, and if possible not connecting the switch and not connecting the red wire (Pack+) from the wiring diagram:
https://github.com/lpollier/battmon/blob/master/example/ERA-201B1_wiring_diagram.png

**Comment by kgh02017** [comment]
Thanks.

>So, I deduce from my assumption that your ERA-201B1 battery pack is close to dead, meaning its cells are not able to power at least the gas gauge alone.
> Can you try to full recharge your battery pack before testing it with the BattMon 2.0 toolkit?

I tried to check with full recharged ERA-201B1 battery (AIBO works 1.5H with this), but no luck.
Now I suspect bad connection with battery.
The voltage between pin1 and pin6 was almost 0V.  Is this correct state ?

**Comment by lpollier** [comment]
OK, so the battery is working well when inserted in the AIBO.

To measure a voltage between Pin 1 (Pack+) and Pin 6 (Pack-), you need to short Pin 4 (/EN) and Pin 6 permanently, ideally with a switch.

But you should also be able to communicate with the bq2040 with only using Pin 2 (SMBus Clock), Pin 3 (SMBus Data) and Pin 6 (Pack-).
The gas gauge is powered internally by the cells. And the Arduino Uno by the USB cable.

**Comment by kgh02017** [comment]
>To measure a voltage between Pin 1 (Pack+) and Pin 6 (Pack-), you need to short Pin 4 (/EN) and Pin 6 permanently, ideally with a switch.

Is the following right ?
The voltage between red and black is almost 0V (about 200mV).


![IMG_4195](https://user-images.githubusercontent.com/32434502/235679335-50c598d7-30c1-4fea-83bf-cf4b5ac3df3e.jpg)

**Comment by lpollier** [comment]
Yes, it should works, you should have the output voltage of about 6.0V-8.4V like this:
![ERA-201B1_switched](https://user-images.githubusercontent.com/42678819/235695398-3b39e60f-fefa-4c5c-83db-1f02ed8078a7.jpg)

**Comment by lpollier** [comment]
So it seem that is one or more pins that are not well connected.
You can find more details with the schematic:
https://github.com/lpollier/battmon/blob/master/example/ERA-201B1_reverse_engineering_schematic.pdf

**Comment by kgh02017** [comment]
Thanks.

When I move the connector to battery slowly, I found that tester sometimes show 8.14V (between 1p-6p voltage)
What type of connector is good for battery connection ?
I use 6pin jumper connector, but this seems to be not good.

**Comment by lpollier** [comment]
Ok, you should try with these 6 pins connectors:
https://a.aliexpress.com/_EGcXjy5

Pitch is 2.5mm and pin thicknesses seems to be 0.6mm.

**Comment by kgh02017** [comment]
Thanks.
I've ordered that.  When I get it, I'll try with it.

**Comment by lpollier** [comment]
Great. I'm going to close this issue.
Let me know if you need help.

Loic
